### ISSUE TITLE
Bang Said boleh di share strategi terbaik di bot turnback buatan abang?

### ISSUE THREAD

**Issue by valeriefaith** [saidforex26/botbinary#2]

**Comment by saidforex26** [comment]
Saya membuatnya dengan permintaan dari seseorang dengan analisa dari 
[СТРАТЕГИЯ_xZ .pdf](https://github.com/saidforex26/botbinary/files/4120676/_xZ.pdf) . analisa tersebut tidak dapat berjalan 24jam . mungkin ada waktuknya bot dapat berhasil pada waktu tertetntu. menurut orang yang pernah mengunakanya. bot dapat berhasil pada waktu binary 09.00 GMT sampai 11.00 GMT  dan 23:00 GMT sampai 01.00 GMT . silahkan anda uji. .

**Comment by valeriefaith** [comment]
terima kasih Bang

**Comment by valeriefaith** [comment]
terima kasih Bang

**Comment by valeriefaith** [comment]
terima kasih Bang
