### ISSUE TITLE
Angka dominan

### ISSUE THREAD

**Issue by valeriefaith** [saidforex26/botbinary#3]
bang saya dapat  bot DD dimana analisa list digitnya berjumlah 10 dengan angka dominan dan angka yang paling banyak muncul.  bagaimanakah logikanya supaya botnya purchase pada angka yang tidak terdapat atau ada  dalam analisa list digitnya?
[DF With Golden Ratio.zip](https://github.com/saidforex26/botbinary/files/4121429/DF.With.Golden.Ratio.zip)

**Comment by saidforex26** [comment]
saya melihat botnya menggunakan digit 0 untuk differs, saya dapat membuat fungsi baru untuk hing dan low digit .

**Comment by valeriefaith** [comment]
Kalau seandainya bot diatas untuk Predictionnya dipilih dari angka yang tidak ada di List digitnya dimana list digitnya terdiri dari 10 angka mis list digitnya 2,3,4,8,9,0,0,7,7,6, maka logic botnya memilih untuk prediction entah angka 1 atau 5. boleh di share logicnya Bang?

**Comment by saidforex26** [comment]
saya pernah mengunakan strategy it. tetapi terkadang los sampai 4x

**Comment by valeriefaith** [comment]
Terima Kasih Bang.
