### ISSUE TITLE
Bot 3 angka 

### ISSUE THREAD

**Issue by valeriefaith** [saidforex26/botbinary#4]
Bang apakah dapat membantu saya membuat bot differ dengan logic mis angka yg muncul 7 2 7 maka LDPnya angka 2. Kalau Last digitnya 5 3 5 maka LDPnya 5 dgn 1 tick. Atau 8 4 8 maka LDpnya angka 4. Terima kasih.

**Comment by saidforex26** [comment]
bisa..   
knp 535 ldpnya 5 sendangkan yang lai ldpnya di tengah

**Comment by valeriefaith** [comment]
Sorry ldpnya 3

**Comment by valeriefaith** [comment]
Boleh di share logic nya dalam bentuk gambar bang?

**Comment by saidforex26** [comment]
anda dapat menentukan digit apa saja yang sama pada list of digits analyzed 
[2DIGIT SAME DARI3DIGITANALISA.zip](https://github.com/saidforex26/botbinary/files/4146299/2DIGIT.SAME.DARI3DIGITANALISA.zip)
![2DIGITSAME](https://user-images.githubusercontent.com/54820719/73626463-f26b4d80-4683-11ea-95ba-52fe71009cad.gif)

**Comment by valeriefaith** [comment]
wow Thanks Bro!

**Comment by valeriefaith** [comment]
Wow thanks Bro.
