### ISSUE TITLE
Ubah strategy beli

### ISSUE THREAD

**Issue by valeriefaith** [saidforex26/botbinary#5]
Bang Said apakah memungkinkan misalnya saya punya 2 strategy beli sebut saja strategy A dan strategy B di blok 2 jika result is win di blok 4 menggunakan strategy A jika result is loss gunakan strategy B. Untuk digit differ. saya sudah coba tapi gagal meski di Run at Once sy sudah set strategy A to true.

**Comment by saidforex26** [comment]
bisa. silahkan berikan strategi atau bot anda

**Comment by valeriefaith** [comment]
Terima kasih untuk responnya Bang.  Adakah no WA yg bisa dihubungi? 
[Differ Change Strategy (1).zip](https://github.com/saidforex26/botbinary/files/4327158/Differ.Change.Strategy.1.zip)

**Comment by saidforex26** [comment]
anda harus mengetahui terkadang binary bot akan erro jika menggunakan last digit dan last digit list.  karena digit terakhir yang digunang dari index AUD bukan index volalitas yg kita pilih.. akhir akhir ini sering terjadi error. tpi saya saya telah memasukan block untuk mengatsi error tersebut dengan munggunakan daftar tik dan mengambil masing2 digit terakhir dari tik...anda dapat melihat block baru dengan nama @lasaidhari membuat text tick.... dan perluh diketahui untuk menjalankan bot digit differ jgan kelamaan karena walupun strategi anda baik tapi anda mengunakan index volalitas yang acak...
[Differ Change Strategy (2).zip](https://github.com/saidforex26/botbinary/files/4327328/Differ.Change.Strategy.2.zip) anda dapat menhubungi saya di fb la said hari copy atau email saidforex26@gmail.com

**Comment by valeriefaith** [comment]
Ok. Terima Kasih untuk tanggapannya serta bantuannya. Terus berkarya dan senantiasa di berkati.

**Comment by valeriefaith** [comment]
Saya sudah coba botnya. Terima kasih sekali lagi, karena botnya berhasil pindah strategi jika loss.

**Comment by saidforex26** [comment]
ya sama sama
